name: Test correo

on:
  push:
    branches:
      - main

jobs:
  test-correo:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar correo de prueba
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: |
          cat > /tmp/mail.txt << MAILEOF
          From: ${GMAIL_USER}
          To: eric.garrido@uchile.cl
          Subject: Probando envio desde GitHub Actions
          MIME-Version: 1.0
          Content-Type: text/plain

          Probando.
          MAILEOF

          curl --ssl-reqd \
            --url "smtps://smtp.gmail.com:465" \
            --user "${GMAIL_USER}:${GMAIL_APP_PASSWORD}" \
            --mail-from "${GMAIL_USER}" \
            --mail-rcpt "eric.garrido@uchile.cl" \
            --upload-file /tmp/mail.txt
            